/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mjj_gaussianblur_GaussianBlur */

#ifndef _Included_com_mjj_gaussianblur_GaussianBlur
#define _Included_com_mjj_gaussianblur_GaussianBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mjj_gaussianblur_GaussianBlur
 * Method:    toGaussianBlur
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mjj_gaussianblur_GaussianBlur_toGaussianBlur
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
